--liquibase formatted sql

--changeset enterprise-ai:003-seed-org-hierarchy
INSERT INTO employees (employee_id, name, department, job_title, email, location, manager_employee_id, access_role, start_date, status)
VALUES
    ('EMP-1001', 'Riley Morgan', 'Executive', 'Chief Executive Officer', 'ceo@company.com', 'Bangalore', NULL, 'executive', '2020-01-15', 'Active'),
    ('EMP-1002', 'Arun Venkatesh', 'Technology', 'Chief Technology Officer', 'cto@company.com', 'Bangalore', 'EMP-1001', 'executive', '2020-01-15', 'Active'),
    ('EMP-1003', 'Jane Doe', 'Engineering', 'Engineering Manager', 'jane.doe@company.com', 'Bangalore', 'EMP-1002', 'manager', '2020-01-15', 'Active'),
    ('EMP-1004', 'Aarav Sharma', 'Engineering', 'Senior Software Engineer', 'aarav.sharma@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1005', 'Priya Patel', 'Engineering', 'Senior Software Engineer', 'priya.patel@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1006', 'Rohan Singh', 'Engineering', 'Senior Software Engineer', 'rohan.singh@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1007', 'Palash Joshi', 'Engineering', 'Senior Software Engineer', 'palash.joshi@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1008', 'Ananya Kumar', 'Engineering', 'Software Engineer', 'ananya.kumar@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1009', 'Vikram Gupta', 'Engineering', 'Software Engineer', 'vikram.gupta@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1010', 'Neha Reddy', 'Engineering', 'Software Engineer', 'neha.reddy@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1011', 'Arjun Iyer', 'Engineering', 'Software Engineer', 'arjun.iyer@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1012', 'Kavya Nair', 'Engineering', 'Software Engineer', 'kavya.nair@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1013', 'Rahul Joshi', 'Engineering', 'Software Engineer', 'rahul.joshi@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1014', 'Sneha Mehta', 'Engineering', 'Software Engineer', 'sneha.mehta@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1015', 'Aditya Kapoor', 'Engineering', 'Software Engineer', 'aditya.kapoor@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1016', 'Isha Malhotra', 'Engineering', 'Junior Software Engineer', 'isha.malhotra@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1017', 'Karan Chopra', 'Engineering', 'Junior Software Engineer', 'karan.chopra@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1018', 'Meera Bhatia', 'Engineering', 'Junior Software Engineer', 'meera.bhatia@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1019', 'Dev Saxena', 'Engineering', 'Junior Software Engineer', 'dev.saxena@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1020', 'Nisha Verma', 'Engineering', 'QA Lead', 'nisha.verma@company.com', 'Bangalore', 'EMP-1003', 'manager', '2020-01-15', 'Active'),
    ('EMP-1021', 'Sanjay Agarwal', 'Engineering', 'QA Engineer', 'sanjay.agarwal@company.com', 'Bangalore', 'EMP-1020', 'employee', '2020-01-15', 'Active'),
    ('EMP-1022', 'Pooja Das', 'Engineering', 'QA Engineer', 'pooja.das@company.com', 'Bangalore', 'EMP-1020', 'employee', '2020-01-15', 'Active'),
    ('EMP-1023', 'Manish Pillai', 'Engineering', 'QA Engineer', 'manish.pillai@company.com', 'Bangalore', 'EMP-1020', 'employee', '2020-01-15', 'Active'),
    ('EMP-1024', 'Divya Rao', 'Engineering', 'DevOps Engineer', 'divya.rao@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1025', 'Nitin Khan', 'Engineering', 'DevOps Engineer', 'nitin.khan@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1026', 'Ritu Ali', 'Engineering', 'UI/UX Designer', 'ritu.ali@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1027', 'Amit Hussain', 'Engineering', 'UI/UX Designer', 'amit.hussain@company.com', 'Bangalore', 'EMP-1003', 'employee', '2020-01-15', 'Active'),
    ('EMP-1028', 'Suresh Menon', 'IT', 'IT Manager', 'it.manager@company.com', 'Bangalore', 'EMP-1002', 'manager', '2020-01-15', 'Active'),
    ('EMP-1029', 'Shreya Fernandes', 'IT', 'System Administrator', 'shreya.fernandes@company.com', 'Bangalore', 'EMP-1028', 'employee', '2020-01-15', 'Active'),
    ('EMP-1030', 'Vivek D''Souza', 'IT', 'System Administrator', 'vivek.d''souza@company.com', 'Bangalore', 'EMP-1028', 'employee', '2020-01-15', 'Active'),
    ('EMP-1031', 'Tanvi Pereira', 'IT', 'Network Engineer', 'tanvi.pereira@company.com', 'Bangalore', 'EMP-1028', 'employee', '2020-01-15', 'Active'),
    ('EMP-1032', 'Gaurav Rodrigues', 'IT', 'IT Support Engineer', 'gaurav.rodrigues@company.com', 'Bangalore', 'EMP-1028', 'employee', '2020-01-15', 'Active'),
    ('EMP-1033', 'Anjali Mukherjee', 'IT', 'IT Support Engineer', 'anjali.mukherjee@company.com', 'Bangalore', 'EMP-1028', 'employee', '2020-01-15', 'Active'),
    ('EMP-1034', 'Harsh Banerjee', 'IT', 'IT Support Engineer', 'harsh.banerjee@company.com', 'Bangalore', 'EMP-1028', 'employee', '2020-01-15', 'Active'),
    ('EMP-1035', 'Lakshmi Narayanan', 'Operations', 'Chief Operating Officer', 'coo@company.com', 'Bangalore', 'EMP-1001', 'executive', '2020-01-15', 'Active'),
    ('EMP-1036', 'Swati Chatterjee', 'Operations', 'Operations Manager', 'swati.chatterjee@company.com', 'Bangalore', 'EMP-1035', 'manager', '2020-01-15', 'Active'),
    ('EMP-1037', 'Yash Smith', 'Operations', 'Operations Executive', 'yash.smith@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1038', 'Preeti Johnson', 'Operations', 'Operations Executive', 'preeti.johnson@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1039', 'Akash Williams', 'Operations', 'Operations Executive', 'akash.williams@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1040', 'Bhavna Brown', 'Operations', 'Operations Executive', 'bhavna.brown@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1041', 'Chetan Jones', 'Operations', 'Office Administrator', 'chetan.jones@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1042', 'Deepa Miller', 'Operations', 'Office Administrator', 'deepa.miller@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1043', 'Sam Wilson', 'Customer Success', 'Customer Success Manager', 'sam.wilson@company.com', 'Bangalore', 'EMP-1035', 'manager', '2020-01-15', 'Active'),
    ('EMP-1044', 'Farhan Davis', 'Customer Success', 'Customer Success Executive', 'farhan.davis@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1045', 'Gita Wilson', 'Customer Success', 'Customer Success Executive', 'gita.wilson@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1046', 'Hemant Anderson', 'Customer Success', 'Customer Success Executive', 'hemant.anderson@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1047', 'Indira Thomas', 'Customer Success', 'Customer Success Executive', 'indira.thomas@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1048', 'Maria Garcia', 'Customer Success', 'Customer Success Executive', 'maria.garcia@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1049', 'James Jackson', 'Customer Success', 'Support Engineer', 'james.jackson@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1050', 'Kelly White', 'Customer Success', 'Support Engineer', 'kelly.white@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1051', 'Liam Harris', 'Customer Success', 'Support Engineer', 'liam.harris@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1052', 'Maya Martin', 'Customer Success', 'Support Engineer', 'maya.martin@company.com', 'Bangalore', 'EMP-1043', 'employee', '2020-01-15', 'Active'),
    ('EMP-1053', 'Anita Desai', 'Finance', 'Chief Financial Officer', 'cfo@company.com', 'Bangalore', 'EMP-1001', 'executive', '2020-01-15', 'Active'),
    ('EMP-1054', 'Noah Thompson', 'Finance', 'Finance Manager', 'noah.thompson@company.com', 'Bangalore', 'EMP-1053', 'manager', '2020-01-15', 'Active'),
    ('EMP-1055', 'Olivia Garcia', 'Finance', 'Accountant', 'olivia.garcia@company.com', 'Bangalore', 'EMP-1054', 'employee', '2020-01-15', 'Active'),
    ('EMP-1056', 'Paul Martinez', 'Finance', 'Accountant', 'paul.martinez@company.com', 'Bangalore', 'EMP-1054', 'employee', '2020-01-15', 'Active'),
    ('EMP-1057', 'Quinn Robinson', 'Finance', 'Accountant', 'quinn.robinson@company.com', 'Bangalore', 'EMP-1054', 'employee', '2020-01-15', 'Active'),
    ('EMP-1058', 'Ryan Clark', 'Finance', 'Payroll Specialist', 'ryan.clark@company.com', 'Bangalore', 'EMP-1054', 'employee', '2020-01-15', 'Active'),
    ('EMP-1059', 'Sara Lewis', 'Finance', 'Finance Analyst', 'sara.lewis@company.com', 'Bangalore', 'EMP-1054', 'employee', '2020-01-15', 'Active'),
    ('EMP-1060', 'Tom Lee', 'Finance', 'Finance Analyst', 'tom.lee@company.com', 'Bangalore', 'EMP-1054', 'employee', '2020-01-15', 'Active'),
    ('EMP-1061', 'Alex Chen', 'HR', 'HR Director', 'alex.chen@company.com', 'Bangalore', 'EMP-1001', 'hr', '2020-01-15', 'Active'),
    ('EMP-1062', 'Uma Walker', 'HR', 'HR Manager', 'uma.walker@company.com', 'Bangalore', 'EMP-1061', 'hr', '2020-01-15', 'Active'),
    ('EMP-1063', 'Victor Hall', 'HR', 'HR Executive', 'victor.hall@company.com', 'Bangalore', 'EMP-1062', 'hr', '2020-01-15', 'Active'),
    ('EMP-1064', 'Wendy Allen', 'HR', 'HR Executive', 'wendy.allen@company.com', 'Bangalore', 'EMP-1062', 'hr', '2020-01-15', 'Active'),
    ('EMP-1065', 'Xavier Young', 'HR', 'HR Executive', 'xavier.young@company.com', 'Bangalore', 'EMP-1062', 'hr', '2020-01-15', 'Active'),
    ('EMP-1066', 'Yolanda King', 'HR', 'Recruiter', 'yolanda.king@company.com', 'Bangalore', 'EMP-1062', 'employee', '2020-01-15', 'Active'),
    ('EMP-1067', 'Zoe Wright', 'HR', 'Recruiter', 'zoe.wright@company.com', 'Bangalore', 'EMP-1062', 'employee', '2020-01-15', 'Active'),
    ('EMP-1068', 'Ethan Scott', 'HR', 'Learning & Development Specialist', 'ethan.scott@company.com', 'Bangalore', 'EMP-1062', 'employee', '2020-01-15', 'Active'),
    ('EMP-1069', 'Fiona Green', 'HR', 'HR Operations Executive', 'fiona.green@company.com', 'Bangalore', 'EMP-1062', 'employee', '2020-01-15', 'Active'),
    ('EMP-1070', 'David Foster', 'Sales', 'Sales Director', 'sales.director@company.com', 'Bangalore', 'EMP-1001', 'executive', '2020-01-15', 'Active'),
    ('EMP-1071', 'George Baker', 'Sales', 'Sales Manager', 'george.baker@company.com', 'Bangalore', 'EMP-1070', 'manager', '2020-01-15', 'Active'),
    ('EMP-1072', 'Hannah Adams', 'Sales', 'Sales Manager', 'hannah.adams@company.com', 'Bangalore', 'EMP-1070', 'manager', '2020-01-15', 'Active'),
    ('EMP-1073', 'Ian Nelson', 'Sales', 'Senior Sales Executive', 'ian.nelson@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1074', 'Julia Carter', 'Sales', 'Senior Sales Executive', 'julia.carter@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1075', 'Kevin Mitchell', 'Sales', 'Senior Sales Executive', 'kevin.mitchell@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1076', 'Laura Perez', 'Sales', 'Senior Sales Executive', 'laura.perez@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1077', 'Marcus Roberts', 'Sales', 'Sales Executive', 'marcus.roberts@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1078', 'Nina Turner', 'Sales', 'Sales Executive', 'nina.turner@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1079', 'Oscar Phillips', 'Sales', 'Sales Executive', 'oscar.phillips@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1080', 'Paula Campbell', 'Sales', 'Sales Executive', 'paula.campbell@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1081', 'Quentin Parker', 'Sales', 'Sales Executive', 'quentin.parker@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1082', 'Rosa Evans', 'Sales', 'Sales Executive', 'rosa.evans@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1083', 'Simon Edwards', 'Sales', 'Sales Executive', 'simon.edwards@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1084', 'Tara Collins', 'Sales', 'Sales Executive', 'tara.collins@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1085', 'Umar Stewart', 'Sales', 'Sales Development Representative', 'umar.stewart@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1086', 'Vera Morris', 'Sales', 'Sales Development Representative', 'vera.morris@company.com', 'Bangalore', 'EMP-1071', 'employee', '2020-01-15', 'Active'),
    ('EMP-1087', 'Walter Rogers', 'Sales', 'Sales Development Representative', 'walter.rogers@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1088', 'Xena Reed', 'Sales', 'Sales Development Representative', 'xena.reed@company.com', 'Bangalore', 'EMP-1072', 'employee', '2020-01-15', 'Active'),
    ('EMP-1089', 'Emily Carter', 'Marketing', 'Marketing Director', 'marketing.director@company.com', 'Bangalore', 'EMP-1001', 'executive', '2020-01-15', 'Active'),
    ('EMP-1090', 'Yusuf Cook', 'Marketing', 'Marketing Manager', 'yusuf.cook@company.com', 'Bangalore', 'EMP-1089', 'manager', '2020-01-15', 'Active'),
    ('EMP-1091', 'Zara Morgan', 'Marketing', 'Digital Marketing Specialist', 'zara.morgan@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1092', 'Blake Bell', 'Marketing', 'Digital Marketing Specialist', 'blake.bell@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1093', 'Chloe Murphy', 'Marketing', 'Content Writer', 'chloe.murphy@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1094', 'Derek Bailey', 'Marketing', 'Content Writer', 'derek.bailey@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1095', 'Elena Rivera', 'Marketing', 'Graphic Designer', 'elena.rivera@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1096', 'Felix Cooper', 'Marketing', 'SEO Specialist', 'felix.cooper@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1097', 'Grace Richardson', 'Marketing', 'Social Media Executive', 'grace.richardson@company.com', 'Bangalore', 'EMP-1090', 'employee', '2020-01-15', 'Active'),
    ('EMP-1098', 'Henry Cox', 'Operations', 'Business Analyst', 'henry.cox@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1099', 'Irene Howard', 'Operations', 'Business Analyst', 'irene.howard@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active'),
    ('EMP-1100', 'Jack Ward', 'Operations', 'Business Analyst', 'jack.ward@company.com', 'Bangalore', 'EMP-1036', 'employee', '2020-01-15', 'Active')
ON CONFLICT (employee_id) DO UPDATE SET
    name = EXCLUDED.name,
    department = EXCLUDED.department,
    job_title = EXCLUDED.job_title,
    email = EXCLUDED.email,
    location = EXCLUDED.location,
    manager_employee_id = EXCLUDED.manager_employee_id,
    access_role = EXCLUDED.access_role,
    start_date = EXCLUDED.start_date,
    status = EXCLUDED.status;

--changeset enterprise-ai:003-link-users-by-email
UPDATE users u
SET employee_id = e.employee_id
FROM employees e
WHERE LOWER(u.email) = LOWER(e.email);
